name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          node-version: 20

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test

  publish-npm:
    name: Create Release Pull Request or Publish to NPM
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          node-version: 20

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          # The pull request title.
          title: 'Changesets Release'
          # The command to update version, edit CHANGELOG, read and delete changesets.
          version: 'npx changeset version'
          # The commit message to use.
          commit: 'chore(changesets): consumed changesets'
          # The command to use to build and publish packages
          publish: 'npx changeset publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
